### ISSUE TITLE
Test flake: Timed out waiting for the WebDriver server

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1684]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/1500/console

```
Error: Timed out waiting for the WebDriver server at http://172.18.8.133:56366/wd/hub
    at Error (native)
    at onResponse (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:87:11)
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:42:21
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
    at ClientRequest.<anonymous> (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/index.js:145:7)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
Fatal error: protractor exited with code: 1
```

**Comment by spadgett** [comment]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/1617/

```
Selenium standalone server started at http://172.18.5.43:37253/wd/hub
ERROR - Unable to start a WebDriver session.

/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
Error: cannot open display: :10
```

**Comment by spadgett** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin_web_console/16
