### ISSUE TITLE
Test flake: User adds an image stream to a project after creating a new project using the Import YAML tab should process and create the images in the image stream

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#1685]
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/1495/console

```
1) User adds an image stream to a project after creating a new project using the Import YAML tab should process and create the images in the image stream
  - Expected false to be true.
      at catalogPage.processImageStream.then (/data/src/github.com/openshift/origin-web-console/test/integration/features/user_adds_imagestream_to_project.spec.js:38:79)
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
    at resolve (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:420:7)
    at fulfill (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:535:5)
    at Object.webdriver.promise.asap (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:776:5)
    at newFrame.onComplete (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1670:25)
```

**Comment by spadgett** [comment]
Related error in https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin_web_console/13/console

1) User adds a template to a project after creating a new project using the Import YAML tab should save the template in the project catalog
  - Error: URL hasn't changed to project/console-test-project-1500489744656/overview(is currently: undefined)
Wait timed out after 5089ms
