### ISSUE TITLE
error with "Install dev dependencies by running hack/install-deps.sh"

### ISSUE THREAD

**Issue by ygp987** [openshift/origin-web-console#3125]
When I Running ./hack/install-deps.sh, there is an build error . so I can't build a development environment. Can somebody help me?
the error log is below.

```
> origin-web-console@3.9.0 postinstall /home/***/********/origin-web-console
> node test/upgrade-selenium.js && node_modules/protractor/bin/webdriver-manager update
fs.js:133
  throw new ERR_INVALID_CALLBACK();
  ^
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:133:9)
    at Object.writeFile (fs.js:1179:14)
    at Object.<anonymous> (/home/ygp/IdeaProjects/origin-web-console/test/upgrade-selenium.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! origin-web-console@3.9.0 postinstall: `node test/upgrade-selenium.js && node_modules/protractor/bin/webdriver-manager update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the origin-web-console@3.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/***/.npm/_logs/2019-04-25T08_21_12_178Z-debug.log

```
and /home/***/.npm/_logs/2019-04-25T08_21_12_178Z-debug.log is below

```
58 verbose stack Error: origin-web-console@3.9.0 postinstall: `node test/upgrade-selenium.js && node_modules/protractor/bin/webdriver-manager update`
58 verbose stack Exit status 1
58 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
58 verbose stack     at EventEmitter.emit (events.js:193:13)
58 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
58 verbose stack     at ChildProcess.emit (events.js:193:13)
58 verbose stack     at maybeClose (internal/child_process.js:999:16)
58 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
59 verbose pkgid origin-web-console@3.9.0
60 verbose cwd /home/***/*******/origin-web-console
61 verbose Linux 4.19.34-1-MANJARO
62 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
63 verbose node v11.14.0
64 verbose npm  v6.9.0
65 error code ELIFECYCLE
66 error errno 1
67 error origin-web-console@3.9.0 postinstall: `node test/upgrade-selenium.js && node_modules/protractor/bin/webdriver-manager update`
67 error Exit status 1
68 error Failed at the origin-web-console@3.9.0 postinstall script.
68 error This is probably not a problem with npm. There is likely additional logging output above.
69 verbose exit [ 1, true ]
```

Thanks a lot.

**Comment by spadgett** [comment]
I suspect that your node version is too new. You could workaround by commenting out the postinstall step in package.json to skip the webdriver manager update.

Note that new console development has moved to https://github.com/openshift/console, which works with the newer node version. This repo is now for maintenance of older releases.

**Comment by ygp987** [comment]
> I suspect that your node version is too new. You could workaround by commenting out the postinstall step in package.json to skip the webdriver manager update.
> 
> Note that new console development has moved to https://github.com/openshift/console, which works with the newer node version. This repo is now for maintenance of older releases.

Thank you very much
