### ISSUE TITLE
bower install fails with node 7

### ISSUE THREAD

**Issue by spadgett** [openshift/origin-web-console#756]
I ran `make clean build`, which resulted in this error. Now whenever I run `hack/install-assets.sh`, I see the same error.

```
Clearing bower cache...
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

cc @jwforres

**Comment by spadgett** [comment]
This seems to be specific to node 7.

**Comment by spadgett** [comment]
Upgrading bower fixes the error. Closing...
